name: bert_mlm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.9.12
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - flatbuffers==24.3.7
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - idna==3.6
      - importlib-metadata==7.1.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==2.1.4
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - zipp==3.18.1
